### ISSUE TITLE
如何下载书箱

### ISSUE THREAD

**Issue by eonezhang** [zeromake/library#1]
您好，
请问要下载仓库中的书籍应该怎么操作呀

**Comment by zeromake** [comment]
这个仓库没有书籍，只是个目录，书籍在我自己的服务器上

**Comment by zeromake** [comment]
要有书籍这个仓库早被删了

**Comment by khl-7732** [comment]
是不是不支持下载了

**Comment by sharefly617** [comment]
那可以下载你的书籍吗？怎么下载呀

**Comment by zeromake** [comment]
@sharefly617 自己想办法，通过其它渠道联系我

**Comment by sharefly617** [comment]
给你邮箱发了个邮件希望能有回复呀！谢谢 @zeromake

**Comment by newhcw** [comment]
@zeromake  我想要 Redis开发与运维.epub 这本书，希望有回复 951123033@qq.com
