### ISSUE TITLE
"Sorry, this is too big to display"訊息 

### ISSUE THREAD

**Issue by MYICEBALL** [zeromake/library#5]
"Sorry, this is too big to display"訊息 在c++/C++ Primer Plus  第6版  中文版.pdf

**Comment by MYICEBALL** [comment]
![Uploading 螢幕擷取畫面 2024-01-27 124715.png…]()

**Comment by MYICEBALL** [comment]
![螢幕擷取畫面 2024-01-27 124715](https://github.com/zeromake/library/assets/156442907/95c32e84-adb4-41dc-82d3-2564c9308567)

**Comment by zeromake** [comment]
> ![螢幕擷取畫面 2024-01-27 124715](https://github.com/zeromake/library/assets/156442907/95c32e84-adb4-41dc-82d3-2564c9308567)
> 

这个仓库里并没有书籍，只是有书籍目录

**Comment by MYICEBALL** [comment]
什麼意思?
在這裡看不到書籍的內容且
書籍目錄太大?

**Comment by MYICEBALL** [comment]
不太懂你的意思

**Comment by zeromake** [comment]
@MYICEBALL ……不懂就不懂吧。
